# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# 所以如果我们要将其放在一个单独的目录中（假设叫 proto ），那么我们应该将 matsuri_pb2_grpc 中的导入逻辑改成这样子
# import matsuri_pb2 as matsuri__pb2
from . import matsuri_pb2 as matsuri__pb2


GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in matsuri_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MatsuriStub(object):
    """编写服务, 每个服务里面有相应的函数(对应 restful 视图函数)
    service 表示创建服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.hello_matsuri = channel.unary_unary(
                '/test.Matsuri/hello_matsuri',
                request_serializer=matsuri__pb2.matsuri_request.SerializeToString,
                response_deserializer=matsuri__pb2.matsuri_response.FromString,
                _registered_method=True)


class MatsuriServicer(object):
    """编写服务, 每个服务里面有相应的函数(对应 restful 视图函数)
    service 表示创建服务
    """

    def hello_matsuri(self, request, context):
        """使用 rpc 定义函数, 参数名为 matsuri_request, 返回值为 matsuri_response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatsuriServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'hello_matsuri': grpc.unary_unary_rpc_method_handler(
                    servicer.hello_matsuri,
                    request_deserializer=matsuri__pb2.matsuri_request.FromString,
                    response_serializer=matsuri__pb2.matsuri_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.Matsuri', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('test.Matsuri', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Matsuri(object):
    """编写服务, 每个服务里面有相应的函数(对应 restful 视图函数)
    service 表示创建服务
    """

    @staticmethod
    def hello_matsuri(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/test.Matsuri/hello_matsuri',
            matsuri__pb2.matsuri_request.SerializeToString,
            matsuri__pb2.matsuri_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
